mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 192.168.0.101
    port: 1883
    #host: 140.112.95.230
    #port: 1884
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:

  # solar ant 
  # velocity command
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: command
    topic_to: /mqtt2ros

  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: geometry_msgs.msg:Twist
    topic_from: cmd
    topic_to: /new_cmd_vel
  # OS command >> reboot shutdown
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: OS
    topic_to: /OS 
  # velocity info  
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Int32
    topic_from: /motor_vl
    topic_to: Left_vel
    
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Int32
    topic_from: /motor_vr
    topic_to: Right_vel
  # IR info  
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ir_front_right
    topic_to: ir_front_right

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ir_front_left
    topic_to: ir_front_left

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ir_back_right
    topic_to: ir_back_right

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ir_back_left
    topic_to: ir_back_left
  # Pose info
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: geometry_msgs.msg:Pose2D
    topic_from: /pose2d
    topic_to: geometryTest
  # Connection State estimate
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Int64
    topic_from: con_fromServer
    topic_to: /connection_stateSub 
  
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Int64
    topic_from: /connection_statePub
    topic_to: con_fromRobot
    
